version: '3.8'

networks:
  skyspecs-network:

services:
  ui-service:
    container_name: skyspecs-ui
    networks:
      - skyspecs-network
    build:
      context: ./ui
    depends_on:
      - api-service
    ports:
      - "3000:3000"

  api-service:
    container_name: skyspecs-api
    networks:
      - skyspecs-network
    build:
      context: ./api
    depends_on:
      - db-service
    ports:
      - "3001:3000"

  db-service:
    container_name: skyspecs-postgres
    networks:
      - skyspecs-network
    image: postgres:alpine
    restart: always
    env_file:
      - ./db/db.env
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"